name: Build and Upload Shadow Jar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build shadow jar
        run: ./gradlew shadowJar

      - name: Upload shadow jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-jar
          path: build/libs/GPlayApiCli.jar
